version: '2'
services:
  vault:
      image: vault
      container_name: vault
      ports:
        - "127.0.0.1:8200:8200"
      volumes:
        - ./file:/vault/file:rw
        - ./config:/vault/config:rw
      cap_add:
        - IPC_LOCK
      entrypoint: vault server -config=/vault/config/vault.json

  vault-ui:
    image: djenriquez/vault-ui
    ports:
      - "8000:8000"
    links:
      - vault
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
    command: ["dev"]